[package]
name = "pokerbootscontracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.4"

# Dev dependencies removed for offline build
[dev-dependencies]

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = []
